#!/bin/bash

RED='\033[0;31m'
GREN='\033[0;32m'
BRWN='\033[0;33m'
BLUE='\033[0;34m'
PURP='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

while true; do
        echo -e $BLUE'['$RED'Start Server Script'$BLUE'] '$CYAN'Starting...'$NC
        ./start_server_helper.sh
        crashes=$(($crashes + 1))
        echo -e $BLUE'['$RED'Start Server Script'$BLUE'] '$CYAN'Stopped...'$NC
        echo -e $BLUE'['$RED'Start Server Script'$BLUE'] '$CYAN'Server has stopped '$BRWN''$crashes''$CYAN' times.'$NC
        sleep 2
done
